### ISSUE TITLE
Hard hat config file problems 

### ISSUE THREAD

**Issue by amrosaeed** [albertov19/uniswap-contracts-moonbeam#1]

**Comment by amrosaeed** [comment]
Invalid value {"url":"https://rpc.testnet.moonbeam.network","accounts":[null],"chainId":1287} for HardhatConfig.networks.moonbase - Expected a value of type HttpNetworkConfig.

**Comment by albertov19** [comment]
Hi @amrosaeed!

This repo is not longer actively being looked over. Please check: https://github.com/PureStake/moonbeam-uniswap
